#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local sysconfig = require 'gluon.sysconfig'

local br
local sr

if sysconfig.gluon_version then

	br = uci:get('wireless', 'radio0', 'basic_rate')
	if br then
		-- do nothing
	else
		sr = uci:get ('wireless', 'radio0', 'supported_rates')
		if sr then
			-- do nothing
		else 
			uci:set_list('wireless', 'radio0', 'basic_rate','6000 9000 12000 24000 54000')
			uci:set_list('wireless', 'radio0', 'supported_rates','6000 9000 12000 18000 24000 36000 48000 54000')
			uci:save('wireless')
			uci:commit('wireless')
		end
	end
end
