#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50

DAEMON=/usr/sbin/mmfd

# TODO only start mmfd after babeld

start_service() {
	procd_open_instance
	procd_set_param command $DAEMON
	procd_append_param command -v
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	local script=$(readlink "$initscript")
	local name=$(basename ${script:-$initscript})

	procd_open_trigger
	procd_add_raw_trigger "interface.*" 0 "/etc/init.d/$name" reload
	procd_close_trigger
}

