#!/usr/bin/lua

local site = require 'gluon.site'
local uci = require("simple-uci").cursor()

uci:set('autoupdater', 'settings', 'branch', site.autoupdater.branch())
uci:set('autoupdater', 'settings', 'enabled', '1')
uci:save('autoupdater')
