#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()

uci:section('fastd', 'fastd', 'mesh_vpn',
          {
                  up = '/lib/gluon/gluon-ffmautokey/on-up',
          }
)

uci:save('fastd')
uci:commit('fastd')
