#!/usr/bin/lua                                                                                                               
                                                                                                                             
local util = require 'gluon.util'                                                                                            
local site = require 'gluon.site'                                                                                     
local sysconfig = require 'gluon.sysconfig'                                                                                  
local uci = require('simple-uci').cursor()                                                                                   
                                                                                                                             
-- Bei einer Erstinstallation, und bei einem Sysupgrade ohne Uebernahme 
-- der 'Einstellungen' werden die Channel der site.conf verwendet.                                                                                                  
--                                                                                                                           
-- Bei einem normalem Sysupgrade werden immer die 'alten' Channel verwenden.                                                       
                                                                                                                             
if sysconfig.gluon_version then           
        -- Setzen des Gluon-internen Flags
        os.execute("uci set gluon-core.@wireless[0].preserve_channels=1")
end                                                                                                                          
                                                                                                                             
uci:save('gluon-core')
