#!/usr/bin/lua
local site = require 'gluon.site_config'
local file = '/etc/collectd.conf'
local host = site.collectd_host
local gutil = require 'gluon.util' 

local NODEID = gutil.node_id()

local f = io.open(file, 'w')
f:write('Hostname    "freifunk-' .. NODEID .. '"\n')
f:write('BaseDir     "/var/lib/collectd"\n')
f:write('PIDFile     "/var/run/collectd.pid"\n')
f:write('Interval    30\n')
f:write('ReadThreads 2\n')
f:write('LoadPlugin cpu\n')
f:write('LoadPlugin interface\n')
f:write('LoadPlugin load\n')
f:write('LoadPlugin network\n')
f:write('LoadPlugin memory\n')
f:write('LoadPlugin ping\n')
f:write('LoadPlugin wireless\n')
f:write('LoadPlugin iwinfo\n')

f:write('#<Plugin interface>\n')
f:write('#	Interface "eth0"\n')
f:write('#	Interface "br-lan"\n')
f:write('#	IgnoreSelected false\n')
f:write('#</Plugin>\n')

f:write('<Plugin network>\n')
f:write('  Server "'.. host ..'" "25827"\n')
f:write('</Plugin>\n')

f:write('<Plugin ping>\n')
f:write('	Host "'.. host .. '"\n')
f:write('	Interval 1.0\n')
f:write('	Timeout 0.9\n')
f:write('	TTL 255\n')
f:write('	Device "br-client"\n')
f:write('	MaxMissed -1\n')
f:write('</Plugin>\n')
