#!/bin/sh /etc/rc.common

START=60

SERVICE_NAME=ffffm-gluon-dnscache
SERVICE_USE_PID=1
SERVICE_PID_FILE=/var/run/gluon-dnscache-dnsmasq.pid


PORT=53
CONFIGFILE=/tmp/gluon-dnscache.conf


start() {
  mkdir -p $(dirname $CONFIGFILE)
  /lib/gluon/ffffm-dnscache/genconfig.lua $CONFIGFILE
  service_start /usr/sbin/dnsmasq -x $SERVICE_PID_FILE -u root -i br-client -p $PORT -h -r $RESOLV_CONF -C $CONFIGFILE
}

stop() {
  service_stop /usr/sbin/dnsmasq
}

