#!/usr/bin/lua                                                                  
                                                                                
-- Alles was in der Datei site.conf steht, wird uebernommen.
-- Leider sind da auch die verwendeten WLAN-Kanaele dabei.
-- Falls Kanal-Optimierungen innerhalb einer Freifunkinstallation
-- duchgefuehrt wurden, so sollten diese jedoch nach einem Upgrade
-- uebernommen werden
--
-- Durch dieses Skript wird sichergestellt, dass nach einem Sysupgrade
-- alle alten Radio-Kanal-Einstellungen wieder hergestellt werden.
-- Unabhaengig, vom Inhalt der site.conf.
--
-- Nach einem Upgrade werden automatisch Skripte von Gluon abgearbeitet.
-- (siehe http://gluon.readthedocs.org/en/latest/dev/upgrade.html )
-- Das neue Skript 110-backup-wireless-channel sicher die Kanal-Einstellungen.
-- Das neue Skript 201-restore-wireless-channel stellt sie wieder her.

local uci = require('luci.model.uci').cursor()                                  
                                                                                
local ch0                                                                       
local ch1                                                                       
                                                                                
-- Falls noch nicht vorhanden,                                                  
-- so wird die Datei /etc/config/keep_settings erzeugt                          
file = io.open("/etc/config/keep_settings", "a")                                
file:close()                                                                    
                                                                                
-- Falls noch nicht vorhanden, so wird die notwendige Section erzeugt.          
uci:set('keep_settings', 'wireless', 'before_upgrade')                          
                                                                                
-- Auslesen und merken des Radio0 Kanals vor dem Sysupgrade                     
ch0 = uci:get('wireless', 'radio0', 'channel')                                  
if ch0 then                                                                     
    uci:set('keep_settings', 'wireless', 'radio0_channel', ch0)                 
end                                                                             
                                                                                
-- Auslesen und merken des Radio1 Kanals vor dem Sysupgrade                     
ch1 = uci:get('wireless', 'radio1', 'channel')                                  
if ch1 then                                                                     
    uci:set('keep_settings', 'wireless', 'radio1_channel', ch1)                 
end                                                                             
                                                                                
-- Sichern der alten Einstellungen                                              
uci:commit('keep_settings')

