#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local sysconfig = require 'gluon.sysconfig'

local ch0
local ch1

if sysconfig.gluon_version then

    ch0 = uci:get('keep_settings', 'wireless', 'radio0_channel')
    if ch0 then
        uci:set('wireless', 'radio0', 'channel', ch0)
    end

    ch1 = uci:get('keep_settings', 'wireless', 'radio1_channel')
    if ch1 then
        uci:set('wireless', 'radio1', 'channel',ch1)
    end
end

uci:save('wireless')
uci:commit('wireless')

