#!/usr/bin/lua

-- Alles was in der Site.conf steht, wird uebernommen.
-- Leider sind da auch die verwendeten WLAN-Kanaele dabei.
-- Falls Kanal-Optimierungen innerhalb einer Freifunkinstallation
-- duchgefuehrt wurden, so sollten diese jedoch uebernommen werden
--
-- Durch dieses Skript werden die alten Kanaele-Einstellungen
-- nach einem Upgradejedoch wieder hergestellt.
-- Unabhaengig, vom Inhalt von site.conf.
--
-- Nach einem Upgrade werden automatisch Skripte von Gluon abgearbeitet.
-- (siehe http://gluon.readthedocs.org/en/latest/dev/upgrade.html )
-- Das neue Skript 110-backup-wireless-channel sicher die Kanal-Einstellungen.
-- Das neue Skript 201-restore-wireless-channel stellt sie wieder her.


local uci = require('luci.model.uci').cursor()

local ch0
local ch1

-- Ruecklesen und speicher des alten Radio0 Kanals
ch0 = uci:get('keep_settings', 'wireless', 'radio0_channel')
if ch0 then
    uci:set('wireless', 'radio0', 'channel', ch0)
end

-- Ruecklesen und speicher des alten Radio1 Kanals
ch1 = uci:get('keep_settings', 'wireless', 'radio1_channel')
if ch1 then
    uci:set('wireless', 'radio1', 'channel',ch1)
end

-- Sichern der alten Einstellungen
uci:commit('wireless')
