#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local lutil = require 'luci.util'

local enabled = uci:get('fastd', 'mesh_vpn', 'auto_mtu_enabled')
if not enabled then
  uci:set('fastd', 'mesh_vpn', 'auto_mtu_enabled','1')
  uci:save('fastd')
  uci:commit('fastd')

end

os.execute('/etc/init.d/automtu enable')
