#!/bin/sh

## Get my own path

path="$( dirname "$0" )"

## Get info about board/hardware and mac address
. /lib/ar71xx.sh

## Key-Upload

"$path/upload_keys" &
echo enabled > /sys/devices/virtual/net/$INTERFACE/batman_adv/no_rebroadcast
exit 0

## MAC-Adresse fuer interface auswuerfeln
oIFS="$IFS"
IFS=":"
set -- $macaddr; IFS="$oIFS"

b2mask=0x02

mac=$(uci get network.freifunk.macaddr)

a=$(echo $mac |sed 's/:/ /g'|cut -d' ' -f 1)
j=$(( 0x$a |$b2mask ))
a=$(echo $mac |sed 's/:/ /g'|cut -d' ' -f 2)
k=$(( 0x$a |$b2mask ))
a=$(echo $mac |sed 's/:/ /g'|cut -d' ' -f 3)
l=$(( 0x$a  |$b2mask ))
a=$(echo $mac |sed 's/:/ /g'|cut -d' ' -f 4)
m=$(( ((0x$a + 1)%256) |$b2mask ))
a=$(echo $mac |sed 's/:/ /g'|cut -d' ' -f 5)
n=$(( 0x$a |$b2mask ))
a=$(echo $mac |sed 's/:/ /g'|cut -d' ' -f 6)
o=$(( 0x$a |$b2mask ))

macaddr=$(printf "%02x:%02x:%02x:%02x:%02x:%02x" $j $k $l $m $n $o)

#macaddr="$( printf "%02x:%s:%s:%02x:%s:%s" $(( 0x$1 | $b2mask )) $2 $3 $(( (0x$4 + 1) % 0x100 )) $5 $6 )"


if [ "$(uci get freifunk.@bandwidth[0].enabled)" -eq 1 ]; then
  tc qdisc add dev "$INTERFACE" root tbf rate "$( uci get freifunk.@bandwidth[0].upstream )kbit" latency 50ms burst 2k

  tc qdisc add dev "$INTERFACE" handle ffff: ingress
  tc filter add dev "$INTERFACE" parent ffff: u32 match u8 00 00 at 0 police rate "$( uci get freifunk.@bandwidth[0].downstream )kbit" burst 10k drop flowid :1
fi



## MAC-Adresse setzen

ip link set address "$macaddr" up dev "$INTERFACE"

( pwd; set ) > /tmp/XXX

exit 0

