#!/usr/bin/lua
local site = require 'gluon.site_config'
local urls = site.key_upload_urls

for url in ipairs(urls) do os.execute('/lib/gluon/gluon-ffmautokey/upload_key_to_server ' .. urls[url] .. ' &') end
