#!/usr/bin/lua

local uci = require('luci.model.uci').cursor()
local sysconfig = require 'gluon.sysconfig'

local ch0
local ch1

file = io.open("/etc/config/keep_settings", "a")
file:close()

uci:set('keep_settings', 'wireless', 'before_upgrade')

uci:delete('keep_settings', 'wireless', 'radio0_channel')
uci:delete('keep_settings', 'wireless', 'radio1_channel')

if sysconfig.gluon_version then

    ch0 = uci:get('wireless', 'radio0', 'channel')
    if ch0 then
        uci:set('keep_settings', 'wireless', 'radio0_channel', ch0)
    end

    ch1 = uci:get('wireless', 'radio1', 'channel')
    if ch1 then
        uci:set('keep_settings', 'wireless', 'radio1_channel', ch1)
    end
end

uci:save('keep_settings')
uci:commit('keep_settings')

